---
title: "Shiny Assignment"
author: "Ali Gökmen"
date: 2022-12-03
format: 
  html:
    toc: true
    code-summary: "Show the code"
---


<style>
    body { 
    font-family: Calibri;
    text-align: justify;
    font-size: 11pt;
    div.hidecode + pre {display: none}
    }
</style>

<div class="hidecode">
```{r setup, output=FALSE,echo=FALSE,warning = FALSE}
knitr::opts_chunk$set(warning = FALSE)
Sys.setlocale(locale = "en_US.UTF-8")
options(dplyr.summarise.inform = FALSE)
```
</div>

Let's invoke the libraries we need in this pre-process

```{r,output=FALSE, warning=FALSE}
library(readxl)
library(tidyr)
library(tidyverse)
library(shiny)

```

Before creating dashboard, let's read and fix the datasets.

```{r}
students <- read_excel("Shiny/foreign_students.xlsx")
saveRDS(students, file = "students.rds")
readRDS(file = "students.rds")
```

```{r}
new_cols <- c("university","type","province","nationality","male","female","total")
colnames(students) <- new_cols

students <- na.omit(students)

students <- students %>% mutate(`female` = as.numeric(`female`))
students <- students %>% mutate(`male` = as.numeric(`male`))
students <- students %>% mutate(`total` = as.numeric(`total`))
```

## Shinyapps.io

<https://ali-gokmen.shinyapps.io/First_Shiny_App/>


```{r, eval = FALSE}
shiny::runGitHub(repo = "pjournal/mef06-ali-gokmen",subdir="/Shiny")
```

